### ISSUE TITLE
Modular concept

### ISSUE THREAD

**Issue by cparrapa** [Open-Hardware-Leaders/OttoDIY#2]
This test card is used to validate ideas and working hypotheses consistently in 4 steps: 1) Hypothesis 2) Experiment 3) Metric 4) Criterion

## 1. Hypothesis: We believe that
A modular robot can make STEAM education more dynamic,  creative, flexible and easy.

## 2. Experiment: To verify it we will do
Use or re-design existing modular systems like the ones use on plastic toys, then we will model and make some samples. the modularity will be analysed and design for both electronics and-or mechanics.

### Materials needed:
- 3D printer
### Tasks
- [x]  Research similar solutions.
- [x]  Explore modular systems and mechanisms.
- [x]  Sketch as many ideas of solutions, focus on the modules.
- [x]  Select 2 to 3 concepts to explore.
- [x]  CAD 1 to 2 of those concepts.
- [x]  Prototype and test just the modules separate.
- [x]  Combine and make functional robots.

## 3. Metric: and we will measure the following indicators
Level of "modularity" (how many robots/devices can made with one set), 
easiness to put together, final size and number of parts per set.

## 4. Criteria: We have partially validated the idea if 
the samples prove to be modular, snap or connect easily and arrange in different places to create at least 2 to 3 type of robots.

**Comment by jbon** [comment]
this is how to make a list in GitHub:
- [x] I haven't done this
- [x] I completed this task
- [x] this is for later

**Comment by jurra** [comment]
@cparrapa Have you seen this? http://www.mindkits.co.nz/makeblock-neuron.aspx
![image](https://user-images.githubusercontent.com/18581201/76626836-2dda2100-653a-11ea-88ef-ac55f996c32e.png)
Could you maybe specify modularity of which functionalities? You could for instance have a bus architecture for modules where you connect them in series for instance. If you combine a set of functionalities you could do a Robot. Can you make a robot out of aggregate pieces of functionality , like blocks that snap to each other? 

I think there are projects around that already acomplish something like this snap feature, but I havent seen it with robots, and definetely not 3D printable. 

The challenge with making it 3D printable is the assembly of the electronics, unless they are standalone small pcbs that you can encapsulate in these 3D printed casings

**Comment by jurra** [comment]
With regard to the assignments of week 5, the basic idea is to breakdown this testcards into more specific tasks. Once you have prioritized your tasks in and push them to the sprint backlog then comes the moment where you want to break down these backlog items into separate tasks. 

This specific test card (experiment) its quite challenging and requires of several improtant tasks. For instance making pcb of specific set of functionalities, designing them and testing them, doing the 3D printable parts, etc.

**Comment by cparrapa** [comment]
Hi @jurra 

Once you research there are actually a lot of solutions that are similar to what we are aiming now, for example:

Little bits (actually Neuron is pretty much a copy of it) which is bus architecture but focus to electronics mainly and is planar, of course at the end you can make almost anything but i want something oriented mostly in robots that will look similar to Otto (cubical). And yes that is exactly the challenge, how to fit a good number of compatible devices/electronics, into as many arrangements as possible that work together. Maybe we will need custom made PCBs for this but i don't wanna go too forward until having a concept clear and for now focus on the structure and proof of concept, using out of shelf sensors, displays and motors etc, electronics can be adapted later.

There is more similar solutions to what we are planning "Modular Robotics with cubelets" "RoboWunderkind" "Tinkerbots" there is a recent KS campaging "Clicbot" all of them very cool and functional but they are expensive and many of them enclose everything so much, that the children do not learn anything, rather than just putting plastic parts together(which is still good but we want to go further)

Not thinking to make the cheapest modular robot neither, but we believe that continuing the DIY approach of Otto combined with 3D printing or maybe other materials, we can fill that gap.

I just specified the experiment more, also added the task here as check list or are we supposed to create additional cards for each of them?

Thanks for the feedback!

**Comment by jurra** [comment]
Breakdown things into tasks if it makes sense, in many cases it makes in my
work. They also can work fine within the issue. Normally when you have "user stories" or hypothesis, it often involves doing several clear intermediate steps. These intermediate steps
(tasks) are often considered during Sprint planning in Scrum also. It is also normal to break them down into separate issues when you are working in a team and you want to assign them to different participants, otherwise it can also work like you have it now :)
